spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
    username:
    password:
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      use-new-id-generator-mappings: false
      ddl-auto: create
    generate-ddl: true
    show-sql: false

search-engine-properties:
  user-agent: PösikEngineSearchBot
  home-page: /admin
  preload:
    sites:
      -
        url: https://nikoartgallery.com
        name: Галерея искусств Niko
      -
        url: https://www.lutherancathedral.ru
        name: Собор Петра и Павла
    fields:
      -
        name: title
        selector: title
        weight: 1.0
      -
        name: body
        selector: body
        weight: 0.8
