spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/search_engine
    username: dms
    password: password
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: false
    show-sql: true
sites:
  url: https://dombulgakova.ru/
  name: Булгаковский дом
