spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/search_engine
    username: search_engine
    password: posikEngine
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      use-new-id-generator-mappings: true
      ddl-auto: create
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        generate_statistics: true

logging:
  file:
    name: PosikEngine_log.log
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss:SSS
  level:
    root: info
    org.hibernate.stat: debug
    org.hibernate.sql: debug
    org.hibernate.cache: debug

search-engine-properties:
  user-agent: PösikEngineSearchBot
  home-page: /admin
  preload:
    sites:
#      -
#        url: https://nikoartgallery.com
#        name: Галерея искусств Niko
      -
        url: https://www.lutherancathedral.ru
        name: Собор Петра и Павла
#      -
#        url: https://et-cetera.ru/mobile
#        name: Театр «Et Cetera»
    fields:
      -
        name: title
        selector: title
        weight: 1.0
      -
        name: body
        selector: body
        weight: 0.8
