spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/search_engine
    username: search_engine
    password: posikEngine
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      use-new-id-generator-mappings: true
      ddl-auto: update
    generate-ddl: true
    properties:
      hibernate:
        jdbc:
          batch_size: 100
        order_updates: true
        order_inserts: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  file:
    name: PosikEngine_log.log
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss:SSS
  level:
    root: info

search-engine-properties:
  user-agent: PösikEngineSearchBot
  home-page: /admin
  preload:
    sites:
      -
        url: https://nikoartgallery.com
        name: Галерея искусств Niko
      -
        url: https://www.lutherancathedral.ru
        name: Собор Петра и Павла
#      -
#        url: https://et-cetera.ru/mobile
#        name: Театр «Et Cetera»
#      -
#        url: https://skillbox.ru
#        name: Skillbox
#      -
#        url: https://playback.ru
#        name: playback
    fields:
      -
        name: title
        selector: title
        weight: 1.0
      -
        name: h1
        selector: h1
        weight: 0.9
      -
        name: body
        selector: body
        weight: 0.8
    authorisations:
      -
        username: webAdmin
        password: webPassword
        role: ROLE_ADMIN
      -
        username: searchUser
        password: searchUserPass
        role: ROLE_SEARCH_API_USER